[package]
name = "thinp"
version = "0.1.0"
authors = ["Joe Thornber <ejt@redhat.com>"]
edition = "2018"
license = "GPL3"

[dependencies]
anyhow = "1.0"
byteorder = "1.3"
clap = "2.33"
crc32c = "0.4"
fixedbitset = "0.3"
futures = "0.3"
flate2 = "1.0"
libc = "0.2.71"
nix = "0.17"
nom = "5.1"
num_cpus = "1.13"
num-derive = "0.3"
num-traits = "0.2"
quick-xml = "0.18"
rand = "0.7"
rio = "0.9"
tempfile = "3.1"
thiserror = "1.0"

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
